name: Run Azure Login with OIDC
on: 
  push:
    branches: 
      - master
    tags:
       - v0.1.0
       - v0.2.0
       - v0.3.0

permissions:
      id-token: write
      contents: read
jobs:
  Azure-Cli-Build-and-Deploy-Resources:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}          
      - name: 'Get Azure Account Information '
        run: |
          az cloud set -n azurecloud
          az account show
          az account list --all -o table
          az group list -o table
          az account list-locations -o table
      - name: 'Create Resoruce Group for LMS Applications ....! '
        run: |
          echo "INFO  - Creating Resource group for LMS Applications"
          echo ""
          az group create -l eastus -n lmsapprg
          echo "INFO  - Creating Storage Account for LMS Applications"
          echo ""
          az storage account create -n lmsappsa -g lmsapprg -l eastus --sku Standard_LRS
          echo "INFO  - Creating Blob Container"
          echo ""
          az storage container create -n lmsapcontainer --account-name lmsappsa
      - name: 'Creating VNet with Subnets'
        run: | 
         az network vnet create --name lms-vnet-01 --resource-group lmsapprg --address-prefix 10.0.0.0/16 --subnet-name subnet-01 --subnet-prefixes 10.0.0.0/24 -l eastus
         az network vnet subnet create --name AzureBastionSubnet --resource-group lmsapprg  --vnet-name lms-vnet-01 --address-prefix 10.0.1.0/26 
      - name: 'Creating PublicIP for LMS APPlication'
        run: |
         az network public-ip create --resource-group lmsapprg --name lmsapp-publicIP --sku Standard --location eastus --zone 1 2 3
         az extension add --name ssh
         az network bastion create --name bastion-host --public-ip-address lmsapp-publicIP --resource-group lmsapprg --vnet-name lms-vnet-01 --location eastus
         az extension add --name ssh
      - name: 'Creating hal-logi-dev Linux Servers'
        run: |
         az vm create --resource-group lmsapprg --admin-username mware --authentication-type password --name hal-logia-d09 --image Ubuntu2204 --public-ip-address ""
         az vm create --resource-group lmsapprg --admin-username mware --authentication-type password --name hal-logia-d10 --image Ubuntu2204 --public-ip-address ""
        
        